# Generated by Django 4.2.6 on 2023-11-17 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='name',
            new_name='Event',
        ),
        migrations.RemoveField(
            model_name='events',
            name='age',
        ),
        migrations.AddField(
            model_name='events',
            name='Date',
            field=models.DateField(default=datetime.date(2023, 11, 17)),
        ),
        migrations.AddField(
            model_name='events',
            name='Time',
            field=models.TimeField(default=datetime.time(17, 59, 33, 956300)),
        ),
    ]
