# Generated by Django 4.2.6 on 2023-11-17 18:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0002_rename_name_events_event_remove_events_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='events',
            name='Time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
